<Project>
  <PropertyGroup>
    <CompletionPackageVersion Condition="'$(CompletionPackageVersion)' == ''">0.1.0-dev.20260916114103</CompletionPackageVersion>
    <CompletionSourceRevision>612b9bc7fec52c4bd3a98b06b64f61e3ead6ef93</CompletionSourceRevision>
    <CompletionRepositoryUrl>https://github.com/Atelia-org/atelia-completion.git</CompletionRepositoryUrl>
    <UseCompletionSources Condition="'$(UseCompletionSources)' == ''">false</UseCompletionSources>
  </PropertyGroup>
</Project>
