using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Atelia.StateJournal.Generators;

internal static class MixedTypeGenerationCommon {
    public const string MixedValueTypeAttributeMetadataName = "Atelia.StateJournal.MixedValueTypeAttribute";
    public const string UseMixedValueCatalogAttributeMetadataName = "Atelia.StateJournal.UseMixedValueCatalogAttribute";

    public static void EmitAttributeSources(IncrementalGeneratorPostInitializationContext context) {
        context.AddSource(
            "MixedValueTypeAttributes.g.cs",
            SourceText.From(
                """
                // <auto-generated/>
                #nullable enable

                namespace Atelia.StateJournal;

                [global::System.Flags]
                internal enum MixedContainers {
                    None = 0,
                    Deque = 1,
                    Dict = 2,
                    OrderedDict = 4,
                    All = Deque | Dict | OrderedDict
                }

                internal enum MixedValueSpecialHandling {
                    None = 0,
                    DurableObject,
                    Symbol
                }

                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
                internal sealed class MixedValueTypeAttribute : global::System.Attribute {
                    public MixedValueTypeAttribute(global::System.Type valueType, global::System.Type faceType, string propertySuffix) {
                        ValueType = valueType;
                        FaceType = faceType;
                        PropertySuffix = propertySuffix;
                    }

                    public global::System.Type ValueType { get; }
                    public global::System.Type FaceType { get; }
                    public string PropertySuffix { get; }
                    public MixedContainers Containers { get; set; } = MixedContainers.All;
                    public MixedValueSpecialHandling SpecialHandling { get; set; } = MixedValueSpecialHandling.None;
                    /// <summary>
                    /// 当 value 类型支持 "caller 移交 buffer 所有权" 的零拷贝入池路径（如 <c>ByteString</c>
                    /// 通过 <c>ByteString.FromTrustedOwned(byte[])</c>），并且 face 类型实现
                    /// <c>ITrustedTypedFace&lt;T&gt;</c> 时设为 true，generator 会额外生成
                    /// <c>UpsertTrusted{PropertySuffix}</c> / <c>PushFrontTrusted{PropertySuffix}</c> 等 opt-in overload。
                    /// </summary>
                    public bool SupportsTrustedFromCallerOwnedBuffer { get; set; }
                }

                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                internal sealed class UseMixedValueCatalogAttribute : global::System.Attribute {
                    public UseMixedValueCatalogAttribute(global::System.Type catalogType, MixedContainers containers) {
                        CatalogType = catalogType;
                        Containers = containers;
                    }

                    public global::System.Type CatalogType { get; }
                    public MixedContainers Containers { get; }
                }
                """,
                Encoding.UTF8
            )
        );
    }

    public static TargetSpec? CreateTarget(GeneratorAttributeSyntaxContext context) {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol || context.TargetNode is not ClassDeclarationSyntax classDeclaration) { return null; }

        AttributeData? useCatalogAttribute = null;
        foreach (var attribute in context.Attributes) {
            if (attribute.AttributeClass?.ToDisplayString() == UseMixedValueCatalogAttributeMetadataName) {
                useCatalogAttribute = attribute;
                break;
            }
        }

        if (useCatalogAttribute is null || useCatalogAttribute.ConstructorArguments.Length < 2) { return null; }

        if (useCatalogAttribute.ConstructorArguments[0].Value is not INamedTypeSymbol catalogTypeSymbol) { return null; }

        int containerMask = useCatalogAttribute.ConstructorArguments[1].Value is int enumAsInt
            ? enumAsInt
            : (int)useCatalogAttribute.ConstructorArguments[1].Value!;

        if (!TryMapContainerKind(containerMask, out var containerKind)) { return null; }

        List<TypeSpec> types = ParseCatalogTypes(catalogTypeSymbol, containerMask);

        if (types.Count == 0) { return null; }

        return new(
            typeSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : typeSymbol.ContainingNamespace.ToDisplayString(),
            typeSymbol.Name,
            typeSymbol.TypeParameters.Select(static x => x.Name).ToImmutableArray(),
            classDeclaration.ConstraintClauses.Select(static x => x.ToString()).ToImmutableArray(),
            containerKind,
            types.ToImmutableArray()
        );
    }

    private static bool TryMapContainerKind(int containerMask, out MixedContainerKind containerKind) {
        switch (containerMask) {
            case (int)MixedContainerKind.Deque:
                containerKind = MixedContainerKind.Deque;
                return true;
            case (int)MixedContainerKind.Dict:
                containerKind = MixedContainerKind.Dict;
                return true;
            case (int)MixedContainerKind.OrderedDict:
                containerKind = MixedContainerKind.OrderedDict;
                return true;
            default:
                containerKind = default;
                return false;
        }
    }

    private static List<TypeSpec> ParseCatalogTypes(INamedTypeSymbol catalogTypeSymbol, int containerMask) {
        List<TypeSpec> types = [];
        foreach (var attribute in catalogTypeSymbol.GetAttributes()) {
            if (attribute.AttributeClass?.ToDisplayString() != MixedValueTypeAttributeMetadataName) { continue; }

            if (attribute.ConstructorArguments.Length < 3) { continue; }

            if (attribute.ConstructorArguments[0].Value is not ITypeSymbol valueType) { continue; }
            if (attribute.ConstructorArguments[1].Value is not ITypeSymbol faceType) { continue; }
            if (attribute.ConstructorArguments[2].Value is not string propertySuffix) { continue; }

            int declaredContainers = (int)MixedContainerKind.All;
            int specialHandling = 0;
            bool supportsTrusted = false;
            foreach (var namedArg in attribute.NamedArguments) {
                if (namedArg.Key == "Containers") {
                    declaredContainers = namedArg.Value.Value is int flagsAsInt
                        ? flagsAsInt
                        : (int)namedArg.Value.Value!;
                }
                else if (namedArg.Key == "SpecialHandling") {
                    specialHandling = namedArg.Value.Value is int specialHandlingAsInt
                        ? specialHandlingAsInt
                        : (int)namedArg.Value.Value!;
                }
                else if (namedArg.Key == "SupportsTrustedFromCallerOwnedBuffer") {
                    supportsTrusted = namedArg.Value.Value is bool b && b;
                }
            }

            if ((declaredContainers & containerMask) == 0) { continue; }

            types.Add(
                new TypeSpec(
                    valueType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    faceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    propertySuffix,
                    valueType.IsValueType,
                    (MixedValueSpecialHandling)specialHandling,
                    supportsTrusted
                )
            );
        }

        return types;
    }

    public static void AppendFilePreamble(StringBuilder builder) {
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable CS8601");
        builder.AppendLine("#pragma warning disable CS8605"); // unboxing of (object?)value after typeof check
        builder.AppendLine("using System.Runtime.CompilerServices;");
        builder.AppendLine();
    }

    public static void AppendNamespace(StringBuilder builder, string? @namespace) {
        if (@namespace is null) { return; }

        builder.Append("namespace ").Append(@namespace).AppendLine(";");
        builder.AppendLine();
    }

    public static void AppendClassHeader(StringBuilder builder, TargetSpec target, string firstInterface, IEnumerable<string> additionalInterfaces) {
        builder.Append("public abstract partial class ").Append(target.TypeName).Append(target.TypeParameterListText);
        builder.Append(" : ").Append(firstInterface);
        foreach (var interfaceType in additionalInterfaces) {
            builder.AppendLine();
            builder.Append("    , ").Append(interfaceType);
        }
        foreach (var constraintClause in target.ConstraintClauses) {
            builder.AppendLine();
            builder.Append("    ").Append(constraintClause);
        }
        builder.AppendLine(" {");
    }

    /// <summary>Partial class header without interface list (interfaces declared in hand-written source).</summary>
    public static void AppendPartialClassHeader(StringBuilder builder, TargetSpec target) {
        builder.Append("public abstract partial class ").Append(target.TypeName).Append(target.TypeParameterListText);
        foreach (var constraintClause in target.ConstraintClauses) {
            builder.AppendLine();
            builder.Append("    ").Append(constraintClause);
        }
        builder.AppendLine(" {");
    }

    internal sealed class TargetSpec {
        public TargetSpec(
            string? @namespace,
            string typeName,
            ImmutableArray<string> typeParameterNames,
            ImmutableArray<string> constraintClauses,
            MixedContainerKind containerKind,
            ImmutableArray<TypeSpec> types
        ) {
            Namespace = @namespace;
            TypeName = typeName;
            TypeParameterNames = typeParameterNames;
            ConstraintClauses = constraintClauses;
            ContainerKind = containerKind;
            Types = types;
        }

        public string? Namespace { get; }
        public string TypeName { get; }
        public ImmutableArray<string> TypeParameterNames { get; }
        public ImmutableArray<string> ConstraintClauses { get; }
        public MixedContainerKind ContainerKind { get; }
        public ImmutableArray<TypeSpec> Types { get; }
        public string TypeParameterListText => TypeParameterNames.Length == 0 ? string.Empty : $"<{string.Join(", ", TypeParameterNames)}>";
        public string JoinedTypeParameterNames => string.Join(", ", TypeParameterNames);
    }

    internal enum MixedContainerKind {
        Deque = 1,
        Dict = 2,
        OrderedDict = 4,
        All = Deque | Dict | OrderedDict,
    }

    internal enum MixedValueSpecialHandling {
        None = 0,
        DurableObject,
        Symbol,
    }

    internal readonly struct TypeSpec {
        public TypeSpec(string valueType, string faceType, string propertySuffix, bool isValueType, MixedValueSpecialHandling specialHandling, bool supportsTrustedFromCallerOwnedBuffer) {
            ValueType = valueType;
            FaceType = faceType;
            PropertySuffix = propertySuffix;
            IsValueType = isValueType;
            SpecialHandling = specialHandling;
            SupportsTrustedFromCallerOwnedBuffer = supportsTrustedFromCallerOwnedBuffer;
        }

        public string ValueType { get; }
        public string FaceType { get; }
        public string PropertySuffix { get; }
        public bool IsValueType { get; }
        public MixedValueSpecialHandling SpecialHandling { get; }
        public bool SupportsTrustedFromCallerOwnedBuffer { get; }

        public string RenderNullableValueType() => IsValueType ? ValueType : $"{ValueType}?";
    }
}
